# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initialize_from_hdf5 <- function(file, name, nrow, ncol, byrow, forced) {
    .Call('_arbalest_initialize_from_hdf5', PACKAGE = 'arbalest', file, name, nrow, ncol, byrow, forced)
}

initialize_from_memory <- function(x, i, p, nrow, ncol, byrow) {
    .Call('_arbalest_initialize_from_memory', PACKAGE = 'arbalest', x, i, p, nrow, ncol, byrow)
}

apply_subset <- function(input, subset, row) {
    .Call('_arbalest_apply_subset', PACKAGE = 'arbalest', input, subset, row)
}

apply_transpose <- function(input) {
    .Call('_arbalest_apply_transpose', PACKAGE = 'arbalest', input)
}

apply_bind <- function(input, row) {
    .Call('_arbalest_apply_bind', PACKAGE = 'arbalest', input, row)
}

apply_addition <- function(input, val, row) {
    .Call('_arbalest_apply_addition', PACKAGE = 'arbalest', input, val, row)
}

apply_multiplication <- function(input, val, row) {
    .Call('_arbalest_apply_multiplication', PACKAGE = 'arbalest', input, val, row)
}

apply_subtraction <- function(input, val, right, row) {
    .Call('_arbalest_apply_subtraction', PACKAGE = 'arbalest', input, val, right, row)
}

apply_division <- function(input, val, right, row) {
    .Call('_arbalest_apply_division', PACKAGE = 'arbalest', input, val, right, row)
}

